server:
  port: 8183
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: fac123
    url: jdbc:postgresql://localhost:5432/msvc_estadopedido
  application:
    name: msvc-calcular

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate:
        SQL: debug


