server:
  port: 8184
datasources:
  portal:
    datasource:
      url: jdbc:postgresql://localhost:5432/msvc_producto
      username: root
      password: fac123
      driverClassName: org.postgresql.Driver