
server:
  port: 8180
spring:
  cloud:
    config:
      server:
        git:
          default-label: luisitodev
          uri: https://github.com/LuisRAnrrango/E-Commerce-KrugerS
          search-paths: config-data
application:
  name: config-service